Patch/common functions relocation
tmaxopensql/orafce pull request #10
Opened 2024-11-19 06:40 UTC by LEEJ0NGWAN

## Classification
- [ ] Feature
- [ ] Hotfix
- [X] Patch
- [ ] Others

## Content
Remove unnecessary third-party sources and functions, and save only the essential functions into new `plvstr.c` file, then relocate the file to the `src/functions` directory.

- deleted files  
  - `src/third-party/*`
  - `tests/third-party/*`
- modified files  
  - `include/builtins.h` Comment out parts of importing unnecessary third-party functions.
  - `src/CMakeLists.txt` Comment out parts of importing the third-party subdirectory.
  - `src/functions/CMakeLists.txt` add the new `plvstr.c` file which have core functions from the original file.
  - `updates/orafce--1.0.sql` Comment out all create function steps of unnecessary functions.
- created files  
  - `src/functions/plvstr.c` A source file refined to extract only the functions used in orafce.

2024-11-19 06:51 UTC, swchangdev commented on include/builtins.h
주석처리 된 부분들 모두 제거하는 게 좋을 것 같습니다. ```plvlex_tokens``` 함수도 마찬가지로 제거해주세요.

2024-11-19 06:51 UTC, swchangdev commented on updates/orafce--1.0.sql
여기도 마찬가지로 주석처리 된 부분 제거 부탁 드립니다.

2024-11-19 06:57 UTC, swchangdev commented on src/functions/CMakeLists.txt
```plvstr.c``` 파일 이름은 적절하지 않습니다. ```string.c```나 ```substr.c```, ```instr.c``` 두 파일로 나누어 관리하는 방법이 더 좋아보입니다.

2024-11-19 06:58 UTC, swchangdev commented on src/functions/plvstr.c
> +
참조된 헤더파일 중 실제로 사용되고 있는 헤더파일이 어떤 것인지 확인해서 필요한 의존성만 갖도록 해야 합니다.

2024-11-19 06:59 UTC, swchangdev commented on src/functions/plvstr.c
> +PG_FUNCTION_INFO_V1(plvstr_instr2);
함수 이름에서도 ```plvstr_``` prefix를 바꿔주세요. 아직 확실히 결정한 건 아니지만, orafce에서 내부에 정의한 함수들의 prefix를 대부분 ```orafce_```로 사용하고 있는 것 같으니 저희도 ```orafce_``` prefix를 사용하는 걸로 하면 좋을 것 같아요.

2024-11-19 07:00 UTC, swchangdev commented on src/functions/plvstr.c
> +PG_FUNCTION_INFO_V1(oracle_substr2);
여기도 ```orafce_``` prefix로 바꿔주세요

2024-11-19 07:00 UTC, swchangdev commented on src/functions/plvstr.c
> +#define ora_substr_text(str, start, len) \
실제 사용하고 있는 macro가 어떤 것인지 확인해서 더이상 사용하지 않는 macro는 지워주세요

2024-11-19 07:04 UTC, swchangdev commented on src/functions/plvstr.c
> +ora_mb_strlen(text *str, char **sizes, int **positions)
이 함수가 ```include/orafce.h```에 extern 함수로 선언되어 있었는데 이제 third-party 코드를 날려버리면서 실제로 사용되는 곳은 해당 파일만 남은 것 같습니다. ```include/orafce.h```에서 선언문을 지우고 해당 파일에 static 함수로 정의하는 게 바람직해 보입니다.

2024-11-19 07:04 UTC, swchangdev commented on src/functions/plvstr.c
> +ora_mb_strlen1(text *str)
해당 함수도 마찬가지로 static 함수로 정의하는 것이 바람직해 보입니다.

2024-11-19 07:06 UTC, swchangdev commented on src/functions/plvstr.c
> +ora_instr(text *txt, text *pattern, int start, int nth)
해당 함수도 마찬가지로 static 함수로 정의하는 것이 바람직해 보입니다.

2024-11-19 07:06 UTC, swchangdev commented on src/functions/plvstr.c
> +/****************************************************************
이런 주석들도 관리 부탁 드립니다.

2024-11-19 07:07 UTC, swchangdev requested changes
Comment 확인해 보시고 궁금한 점 있으면 알려주세요.

2024-11-19 08:45 UTC, LEEJ0NGWAN commented on src/functions/CMakeLists.txt
함수양이 많지 않고, 기존 함수 소스들이 하나의 주제에 대해 c파일 하나로 관리(math.c) 하는 것 같아 string.c 라는 하나의 소스로 두었습니다

2024-11-19 08:46 UTC, LEEJ0NGWAN commented on src/functions/plvstr.c
> +
빌드 테스트 진행하여 필수 의존성만 include처리하였습니다.

2024-11-19 08:48 UTC, LEEJ0NGWAN commented on src/functions/plvstr.c
> +PG_FUNCTION_INFO_V1(plvstr_instr2);
내부 함수들의 prefix를 전부 orafce_ 로 통일하였습니다 (static 함수들도 prefix를 ora_ 에서 orafce_로 변경하였습니다)

2024-11-19 08:49 UTC, LEEJ0NGWAN commented on src/functions/plvstr.c
> +PG_FUNCTION_INFO_V1(oracle_substr2);
적용하였습니다

2024-11-19 08:56 UTC, LEEJ0NGWAN commented on src/functions/plvstr.c
> +#define ora_substr_text(str, start, len) \
#define 되어있는 매크로 모두 불필요하여 제거하였습니다
매크로 중 `PARAMETER_ERROR` 라는 에러 레포트 출력 매크로만 코드 내부에서 딱 1곳 사용하고 있었습니다만, 1곳 밖에 사용처가 없어서 매크로 제거 후 define 되어 있던 로직을 해당 부분에 직접 삽입하였습니다.

2024-11-19 08:56 UTC, LEEJ0NGWAN commented on src/functions/plvstr.c
> +ora_mb_strlen(text *str, char **sizes, int **positions)
static 처리 후 prefix를 orafce로 통일하였습니다

2024-11-19 08:56 UTC, LEEJ0NGWAN commented on src/functions/plvstr.c
> +ora_mb_strlen1(text *str)
static 처리 후 prefix를 orafce로 통일하였습니다

2024-11-19 08:57 UTC, LEEJ0NGWAN commented on src/functions/plvstr.c
> +/****************************************************************
실제 제공되는 함수 포맷 ( `oracle.instr`, `oracle.substr`, `oracle.substrb`) 에 맞춰 주석 수정하였습니다

2024-11-19 23:59 UTC, swchangdev commented on src/functions/plvstr.c
> +
builtin.h 도 같이 제거되었던데 pgtap 정상적으로 동작하던가요?

2024-11-20 00:00 UTC, LEEJ0NGWAN commented on src/functions/plvstr.c
> +
넵 제가 새로 빌드하고 pg_prove으로 pgtap 테스트 진행할때는 이상 없었습니다

2024-11-20 00:13 UTC, swchangdev commented on updates/orafce--1.0.sql
> +-- GRANT USAGE ON SCHEMA plunit TO PUBLIC;
여기에도 주석이 하나 더 남아있네요

2024-11-20 00:19 UTC, LEEJ0NGWAN commented on updates/orafce--1.0.sql
> +-- GRANT USAGE ON SCHEMA plunit TO PUBLIC;
> 여기에도 주석이 하나 더 남아있네요

헉 적용하였습니다

2024-11-20 00:19 UTC, swchangdev approved these changes
Good Job :)

2024-11-20 00:20 UTC, merged